# Generated by Django 4.2.6 on 2023-10-18 21:31

from django.db import migrations, models
import django.db.models.deletion
import owly.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('contacto', models.EmailField(max_length=254)),
                ('comisiones', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='APIKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=64, unique=True)),
                ('description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='AvanceDeObra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre del Avance')),
                ('demolición', models.PositiveIntegerField(default=0, verbose_name='Demolición')),
                ('excavación', models.PositiveIntegerField(default=0, verbose_name='Excavación')),
                ('estructura', models.PositiveIntegerField(default=0, verbose_name='Estructura')),
                ('fachada', models.PositiveIntegerField(default=0, verbose_name='Fachada')),
                ('hidráulica', models.PositiveIntegerField(default=0, verbose_name='Hidráulica')),
                ('eléctrica', models.PositiveIntegerField(default=0, verbose_name='Eléctrica')),
                ('extracción', models.PositiveIntegerField(default=0, verbose_name='Extracción')),
                ('mampostería_liviana', models.PositiveIntegerField(default=0, verbose_name='Mampostería Liviana')),
                ('avance_total', models.PositiveIntegerField(default=0, verbose_name='Avance total')),
            ],
        ),
        migrations.CreateModel(
            name='Caracteristica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Constructora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('logo', models.ImageField(upload_to=owly.models.constructora_logo_upload_path)),
            ],
        ),
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ciudad', models.CharField(max_length=255)),
                ('region_estado', models.CharField(max_length=255)),
                ('pais', models.CharField(max_length=255)),
                ('coordenadas', models.CharField(max_length=255)),
                ('calle', models.CharField(max_length=255)),
                ('codigo', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('logo', models.ImageField(upload_to=owly.models.empresa_logo_upload_path)),
                ('rol', models.CharField(max_length=100)),
                ('constructora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='owly.constructora')),
            ],
        ),
        migrations.CreateModel(
            name='Etapa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('numero_de_etapa', models.PositiveIntegerField()),
                ('numero_de_torres', models.PositiveIntegerField()),
                ('fecha_entrega_estimada', models.DateField()),
                ('porcentaje_cuota_inicial', models.PositiveIntegerField()),
                ('avance_obra', models.ManyToManyField(to='owly.avancedeobra')),
                ('caracteristicas', models.ManyToManyField(to='owly.caracteristica')),
            ],
        ),
        migrations.CreateModel(
            name='Etiqueta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('puntos', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Imagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=255)),
                ('imagen', models.ImageField(upload_to=owly.models.imagen_upload_path)),
                ('constructora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='owly.constructora')),
            ],
        ),
        migrations.CreateModel(
            name='Inmueble',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_descripcion', models.CharField(max_length=255)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=24)),
                ('habitaciones', models.IntegerField()),
                ('piso', models.IntegerField()),
                ('baños', models.DecimalField(decimal_places=1, max_digits=3)),
                ('terraza', models.BooleanField()),
                ('externo', models.BooleanField()),
                ('estado', models.CharField(max_length=255)),
                ('caracteristicas', models.ManyToManyField(to='owly.caracteristica')),
                ('etiquetas', models.ManyToManyField(to='owly.etiqueta')),
                ('imagenes', models.ManyToManyField(to='owly.imagen')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=255)),
                ('contrasena', models.CharField(max_length=255)),
                ('rol', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Torre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_descripcion', models.CharField(max_length=255)),
                ('Etapa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='owly.etapa')),
                ('imagenes', models.ManyToManyField(to='owly.imagen')),
            ],
        ),
        migrations.CreateModel(
            name='Tipologia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.CharField(max_length=255)),
                ('cantidad', models.IntegerField()),
                ('imagenes', models.ManyToManyField(to='owly.imagen')),
            ],
        ),
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('estado', models.CharField(max_length=255)),
                ('inmueble', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='owly.inmueble')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='owly.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Reservacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('estado', models.CharField(max_length=255)),
                ('inmueble', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='owly.inmueble')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='owly.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Resena',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('titulo', models.CharField(max_length=255)),
                ('comentario', models.CharField(max_length=255)),
                ('puntuacion', models.CharField(max_length=255)),
                ('inmueble', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='owly.inmueble')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='owly.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('imagen', models.ImageField(upload_to=owly.models.proyecto_imagen_upload_path)),
                ('logo', models.ImageField(upload_to=owly.models.proyecto_logo_upload_path)),
                ('numero_etapas', models.PositiveIntegerField()),
                ('Empresa', models.ManyToManyField(to='owly.empresa')),
                ('avance_obra', models.ManyToManyField(to='owly.avancedeobra')),
                ('caracteristicas', models.ManyToManyField(to='owly.caracteristica')),
                ('constructora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='owly.constructora')),
                ('direccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='owly.direccion')),
            ],
        ),
        migrations.CreateModel(
            name='Promocion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=255)),
                ('fecha', models.DateField()),
                ('descuento', models.CharField(max_length=255)),
                ('inmuebles', models.ManyToManyField(to='owly.inmueble')),
            ],
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('fecha', models.DateField()),
                ('metodo', models.CharField(max_length=255)),
                ('estado', models.CharField(max_length=255)),
                ('inmueble', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='owly.inmueble')),
            ],
        ),
        migrations.AddField(
            model_name='inmueble',
            name='tipologia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='owly.tipologia'),
        ),
        migrations.AddField(
            model_name='inmueble',
            name='torre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='owly.torre'),
        ),
        migrations.CreateModel(
            name='Historial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('inmueble', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='owly.inmueble')),
            ],
        ),
        migrations.CreateModel(
            name='Favorito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('inmueble', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='owly.inmueble')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='owly.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=255)),
                ('fecha', models.DateField()),
                ('tipo', models.CharField(max_length=255)),
                ('prioridad_severidad', models.CharField(max_length=255)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='owly.usuario')),
            ],
        ),
        migrations.AddField(
            model_name='etapa',
            name='proyecto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='owly.proyecto'),
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_descripcion', models.CharField(max_length=255)),
                ('tipo', models.CharField(max_length=255)),
                ('fecha', models.DateField()),
                ('agente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='owly.agente')),
                ('inmueble', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='owly.inmueble')),
            ],
        ),
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario_cliente', models.CharField(max_length=255)),
                ('fecha', models.DateField()),
                ('terminos', models.CharField(max_length=255)),
                ('agente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='owly.agente')),
                ('inmueble', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='owly.inmueble')),
            ],
        ),
        migrations.AddField(
            model_name='agente',
            name='inmuebles',
            field=models.ManyToManyField(to='owly.inmueble'),
        ),
        migrations.CreateModel(
            name='Actualizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('inmueble', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='owly.inmueble')),
            ],
        ),
    ]
