# Generated by Django 4.2.6 on 2023-10-18 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('owly', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='avancedeobra',
            old_name='demolición',
            new_name='demolicion',
        ),
        migrations.RenameField(
            model_name='avancedeobra',
            old_name='eléctrica',
            new_name='electrica',
        ),
        migrations.RenameField(
            model_name='avancedeobra',
            old_name='excavación',
            new_name='excavacion',
        ),
        migrations.RenameField(
            model_name='avancedeobra',
            old_name='extracción',
            new_name='extraccionn',
        ),
        migrations.RenameField(
            model_name='avancedeobra',
            old_name='hidráulica',
            new_name='hidraulica',
        ),
        migrations.RenameField(
            model_name='avancedeobra',
            old_name='mampostería_liviana',
            new_name='mamposteria_liviana',
        ),
    ]
