# Generated by Django 4.2.6 on 2023-10-18 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('owly', '0003_alter_avancedeobra_demolicion_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='avancedeobra',
            old_name='extraccionn',
            new_name='extraccion',
        ),
    ]
